### PR TITLE
Fix calculations for damps_ , hsig_ and artmp variables

### PR DESCRIPTION
**Pull request by ajikmr**
Fixed equations for three variable damps_ , hsig_ and artmp in CMA-ES optimizer.

Have not run unit tests.

### CODE REVIEW

**Comment by Bellout** [comment]
Thanks for your contribution @ajkmr-data. I've asked the implementer of this code (@bragesk) to take a look.

**Review by bragesk — APPROVED** [review]
Perfect, thank you for your contribution!

**Comment by ajikmr** [comment]
This was my first git pull request. Hoping to make some more contributions.

**Comment by Bellout** [comment]
> This was my first git pull request. Hoping to make some more contributions.

Hi Ajitabh, very good. Do let us know about your use of the software as you proceed. 

You can try out FieldOpt-Research-Open, but it is meant for more experimental work.

Regular FieldOpt is somewhat stale at the moment, but it is a good starting point.

**Comment by ajikmr** [comment]
Hello Mathias. I use FieldOpt for research purposes as it enables to quickly try out different algorithms. I will check out FieldOpt-Research-Open version as well. It seems there are some more algorithms in that repository.

**Pull request merged**
