### PR TITLE
Feature/tuesday 2016 06 28

### PR DESCRIPTION
**Pull request by Bellout**
Works, but there is likely a much simpler way to implement specifying the FieldOpt build folder at runtime, and in particular, of passing this variable around (here: to AdgprsResultsReader). We can discuss further if needed.

### CODE REVIEW

**Comment by einar90** [comment]
Use descriptive names for feature branches.

**Comment by Bellout** [comment]
Looked through. Looks good. Another approach I contemplated yesterday was implementing GetBuildDir as a static function in Utitlities::FileHandling (as it originally was, but now with the ability to return the runtime specified build dir). This would have made this variable much easier to call from different places in the code (not that I see any other places right now where this would be needed, nor in the future, but for generality). However, the burden is then on sending the value from the settings object (which is a dynamic entity) to the static function, and, I don't know, but I assume there are some issues in combining these two types of function mode. 
Merge and delete branch whenever you see fit.

**Comment by einar90** [comment]
You're correcty in assuming there are issues. Precisely because it is a static function, getting the build dir from the runtime settings would not make things any easier at all, seeing that you would have to pass the path it self in as an argument every time in order to access it in the function, because static functions are state-less. 

And you're not really passing the path around (well, you are, but this is nothing new): you're setting it in the Settings object, which is already passed around wherever settings are needed.

**Comment by Bellout** [comment]
Good stuff. Thanks.

**Pull request closed without merging**
